#server:
#  port: 7088
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/yunemr?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    database: mysql
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
#
#
